var nationJsonArray = [{
    "value": 1,
    "pinyin": "hz",
    "label": "汉族"
}, {
    "value": 2,
    "pinyin": "zz",
    "label": "藏族"
}, {
    "value": 3,
    "pinyin": "zz",
    "label": "壮族"
}, {
    "value": 4,
    "pinyin": "mz",
    "label": "满族"
}, {
    "value": 5,
    "pinyin": "hz",
    "label": "回族"
}, {
    "value": 6,
    "pinyin": "mz",
    "label": "苗族"
}, {
    "value": 7,
    "pinyin": "wwez",
    "label": "维吾尔族"
}, {
    "value": 8,
    "pinyin": "tjz",
    "label": "土家族"
}, {
    "value": 9,
    "pinyin": "yz",
    "label": "彝族"
}, {
    "value": 10,
    "pinyin": "mgz",
    "label": "蒙古族"
}, {
    "value": 11,
    "pinyin": "byz",
    "label": "布依族"
}, {
    "value": 12,
    "pinyin": "dz",
    "label": "侗族"
}, {
    "value": 13,
    "pinyin": "yz",
    "label": "瑶族"
}, {
    "value": 14,
    "pinyin": "cxz",
    "label": "朝鲜族"
}, {
    "value": 15,
    "pinyin": "bz",
    "label": "白族"
}, {
    "value": 16,
    "pinyin": "hnz",
    "label": "哈尼族"
}, {
    "value": 17,
    "pinyin": "hskz",
    "label": "哈萨克族"
}, {
    "value": 18,
    "pinyin": "lz",
    "label": "黎族"
}, {
    "value": 19,
    "pinyin": "dz",
    "label": "傣族"
}, {
    "value": 20,
    "pinyin": "sz",
    "label": "畲族"
}, {
    "value": 21,
    "pinyin": "lsz",
    "label": "傈僳族"
}, {
    "value": 22,
    "pinyin": "glz",
    "label": "仡佬族"
}, {
    "value": 23,
    "pinyin": "dxz",
    "label": "东乡族"
}, {
    "value": 24,
    "pinyin": "gsz",
    "label": "高山族"
}, {
    "value": 25,
    "pinyin": "lhz",
    "label": "拉祜族"
}, {
    "value": 26,
    "pinyin": "sz",
    "label": "水族"
}, {
    "value": 27,
    "pinyin": "wz",
    "label": "佤族"
}, {
    "value": 28,
    "pinyin": "nxz",
    "label": "纳西族"
}, {
    "value": 29,
    "pinyin": "qz",
    "label": "羌族"
}, {
    "value": 30,
    "pinyin": "tz",
    "label": "土族"
}, {
    "value": 31,
    "pinyin": "mlz",
    "label": "仫佬族"
}, {
    "value": 32,
    "pinyin": "xbz",
    "label": "锡伯族"
}, {
    "value": 33,
    "pinyin": "kekzz",
    "label": "柯尔克孜族"
}, {
    "value": 34,
    "pinyin": "dwez",
    "label": "达斡尔族"
}, {
    "value": 35,
    "pinyin": "jpz",
    "label": "景颇族"
}, {
    "value": 36,
    "pinyin": "mnz",
    "label": "毛南族"
}, {
    "value": 37,
    "pinyin": "lsz",
    "label": "撒拉族"
}, {
    "value": 38,
    "pinyin": "tjkz",
    "label": "塔吉克族"
}, {
    "value": 39,
    "pinyin": "acz",
    "label": "阿昌族"
}, {
    "value": 40,
    "pinyin": "pmz",
    "label": "普米族"
}, {
    "value": 41,
    "pinyin": "ewkz",
    "label": "鄂温克族"
}, {
    "value": 42,
    "pinyin": "nz",
    "label": "怒族"
}, {
    "value": 43,
    "pinyin": "nz",
    "label": "怒族"
}, {
    "value": 44,
    "pinyin": "jz",
    "label": "京族"
}, {
    "value": 45,
    "pinyin": "jnz",
    "label": "基诺族"
}, {
    "value": 46,
    "pinyin": "daz",
    "label": "德昂族"
}, {
    "value": 47,
    "pinyin": "baz",
    "label": "保安族"
}, {
    "value": 48,
    "pinyin": "elsz",
    "label": "俄罗斯族"
}, {
    "value": 49,
    "pinyin": "ygz",
    "label": "裕固族"
}, {
    "value": 50,
    "pinyin": "wzbkz",
    "label": "乌兹别克族"
}, {
    "value": 51,
    "pinyin": "mbz",
    "label": "门巴族"
}, {
    "value": 52,
    "pinyin": "elcz",
    "label": "鄂伦春族"
}, {
    "value": 53,
    "pinyin": "dlz",
    "label": "独龙族"
}, {
    "value": 54,
    "pinyin": "ttez",
    "label": "塔塔尔族"
}, {
    "value": 55,
    "pinyin": "hzz",
    "label": "赫哲族"
}, {
    "value": 56,
    "pinyin": "lbz",
    "label": "珞巴族"
}];


module.exports = nationJsonArray;